function initial_gen = generateInitialGeneration( pop_size, ...
                        gate_matrix_size,...
                        gate_string_size,...
                        gate_types )  % Range of gate types!
    initial_gen = cell(pop_size,2); %pre allocation
    for i=1:pop_size
        initial_gen{i,1} = randomBinaryString...
                    ([1 gate_string_size(2)]);  % binary string
        initial_gen{i,2} = round( gate_types*rand(gate_matrix_size) );      
    end
end
